OUT="definitions.h"

DISCLAIMER="""\
/* DON'T edit this file: it is autogenerated
 *
 * Instead, make changes to generate_defs.py and then run
 *
 *   python generate_defs.py
 *
 */
"""

BASSES = ["C","Db","D","Eb","E","F","Gb","G","Ab","A","Bb","B"]

"""

increments:
0   .00  .24  .54  .22
1   .02  .26  .52  .20
2   .04  .28  .50  .18
3   .06  .30  .48  .16
4   .08  .32  .46  .14
5   .10  .34  .44  .12
6   .12  .36  .42  .10
7   .14  .38  .40  .08
8   .16  .40  .38  .06
9   .18  .42  .36  .04
10  .20  .44  .34  .02
11  .22  .46  .32  .00

"""

def freq(note):
    return 440*(2**((note-69.0)/12));

def fraction(bass_n, octave):
    root = [0.00, 0.12, 0.24, 0.32, 0.22, 0.10][octave]

    if octave in [0,1,2]:
        root += 0.01*bass_n
    else:
        root -= 0.01*bass_n

    if root < 0:
        root = 0    

    return root

'''
for bass in BASSES:
    print bass,
print
for octave in [0,1,2,3,4,5]:
    for bass_n, bass in enumerate(BASSES):
        print fraction(bass_n, octave),
    print
'''

for bass_n, bass in enumerate(BASSES):
    for octave in [0,1,2,3,4,5]:
        print bass, freq(bass_n+12*octave), fraction(bass_n, octave)

def start():
    with open(OUT, "w") as outf:
        w = outf.write
        w(DISCLAIMER)

        for n in range(128):
            f = 440*(2**((n-69.0)/12))
            w("#define NOTE_%s %s\n" % (n, f))

        for octave in [0,1,2,3,4,5,6,7]:
            for bass_n, bass in enumerate(BASSES):
                note_n = 12 + octave*12 + bass_n
                w("#define NOTE_%s%s NOTE_%s\n" % (bass, octave, note_n))

if __name__ == "__main__":
    start()
